import { useEffect, useState } from 'react'
const rupiah=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n||0))
export default function Admin(){const[auth,setAuth]=useState(false),[stats,setStats]=useState(null),[orders,setOrders]=useState([]),[products,setProducts]=useState([]),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false)
  async function load(){const a=await fetch('/api/admin/overview');if(a.status===401){setAuth(false);return}const d=await a.json();if(!a.ok){setMsg(d.error);return}setAuth(true);setStats(d.stats);const [o,p]=await Promise.all([fetch('/api/admin/orders').then(r=>r.json()),fetch('/api/admin/products').then(r=>r.json())]);setOrders(o.orders||[]);setProducts(p.products||[])}
  useEffect(()=>{load().catch(()=>{})},[])
  async function login(e){e.preventDefault();setBusy(true);setMsg('');const body=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();setBusy(false);if(!r.ok)return setMsg(d.error);setAuth(true);load()}
  async function patch(code,patch){await fetch('/api/admin/orders',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({code,...patch})});load()}
  async function addProduct(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));f.price=Number(f.price);f.features=String(f.features||'').split(',').map(x=>x.trim()).filter(Boolean);const r=await fetch('/api/admin/products',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(f)});const d=await r.json();if(!r.ok)return setMsg(d.error);e.currentTarget.reset();load()}
  async function logout(){await fetch('/api/admin/logout',{method:'POST'});setAuth(false)}
  if(!auth)return <main className="adminLogin"><div className="loginBox"><a className="brand" href="/"><span className="mark">D</span>DiTz Store</a><span className="eyebrow">SECURE ADMIN</span><h1>Admin Panel</h1><p>Kredensial dibaca dari environment server dan session disimpan di cookie HttpOnly.</p><form className="form" onSubmit={login}><label>Username<input name="username" required autoComplete="username"/></label><label>Password<input name="password" type="password" required autoComplete="current-password"/></label>{msg&&<div className="warning">{msg}</div>}<button className="btn primary big full" disabled={busy}>{busy?'Memeriksa...':'Masuk admin'}</button></form></div></main>
  return <main className="admin"><aside><a className="brand" href="/"><span className="mark">D</span>DiTz Admin</a><nav><a href="#overview">Overview</a><a href="#orders">Pesanan</a><a href="#products">Produk</a></nav><button className="btn" onClick={logout}>Keluar</button></aside><section><div className="adminTop"><div><span className="eyebrow">CONTROL CENTER</span><h1>Dashboard</h1></div><a className="btn" href="/">Buka toko ↗</a></div>{msg&&<div className="warning">{msg}</div>}
    <div id="overview" className="stats">{[['Pesanan',stats?.orders],['Pending',stats?.pending],['Paid',stats?.paid],['Revenue',rupiah(stats?.revenue)]].map(([a,b])=><div key={a}><span>{a}</span><b>{b??'-'}</b></div>)}</div>
    <div id="orders" className="adminCard"><div className="adminCardHead"><div><span className="eyebrow">ORDERS</span><h2>Pesanan terbaru</h2></div><button className="btn" onClick={load}>Refresh</button></div><div className="tableWrap"><table><thead><tr><th>Kode</th><th>Pelanggan</th><th>Total</th><th>Status</th><th>Pembayaran</th></tr></thead><tbody>{orders.map(o=><tr key={o.code}><td><b>{o.code}</b><small>{new Date(o.created_at).toLocaleString('id-ID')}</small></td><td>{o.customer_name}<small>{o.customer_email}</small></td><td>{rupiah(o.total)}</td><td><select value={o.status} onChange={e=>patch(o.code,{status:e.target.value})}><option>pending</option><option>processing</option><option>completed</option><option>cancelled</option></select></td><td><select value={o.payment_status} onChange={e=>patch(o.code,{paymentStatus:e.target.value})}><option>unpaid</option><option>paid</option><option>failed</option><option>refunded</option></select></td></tr>)}</tbody></table></div></div>
    <div id="products" className="adminGrid"><div className="adminCard"><div className="adminCardHead"><div><span className="eyebrow">CATALOG</span><h2>Produk aktif</h2></div><b>{products.length}</b></div><div className="adminProducts">{products.map(p=><div key={p.id}><span>{p.icon||'◆'}</span><div><b>{p.name}</b><small>{p.category} • {rupiah(p.price)}</small></div><i className={p.active?'live':'warn'}>{p.active?'AKTIF':'OFF'}</i></div>)}</div></div><div className="adminCard"><span className="eyebrow">ADD PRODUCT</span><h2>Tambah produk</h2><form className="form" onSubmit={addProduct}><label>Nama<input name="name" required/></label><div className="twoFields"><label>Kategori<input name="category" required/></label><label>Harga<input name="price" type="number" min="1" required/></label></div><label>Deskripsi<textarea name="description" rows="3"/></label><label>Fitur <small>(pisahkan dengan koma)</small><input name="features" placeholder="Responsive, SEO, Admin"/></label><div className="twoFields"><label>Badge<input name="badge" placeholder="NEW"/></label><label>Icon<input name="icon" placeholder="◆"/></label></div><button className="btn primary big full">Tambah ke katalog</button></form></div></div>
  </section></main>}
